In [13]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("charges_by_agegroup.csv")
df.head()

age_group aggtype       Charges
0  (17.999, 21.0]   count  1.940000e+02
1  (17.999, 21.0]     sum  1.578891e+06
2  (17.999, 21.0]    mean  8.138614e+03
3    (21.0, 27.0]   count  1.680000e+02
4    (21.0, 27.0]     sum  1.714655e+06

In [5]:
df.T

0               1               2             3   \
age_group  (17.999, 21.0]  (17.999, 21.0]  (17.999, 21.0]  (21.0, 27.0]   
aggtype             count             sum            mean         count   
Charges               194     1.57889e+06         8138.61           168   

                     4             5             6             7   \
age_group  (21.0, 27.0]  (21.0, 27.0]  (27.0, 33.0]  (27.0, 33.0]   
aggtype             sum          mean         count           sum   
Charges     1.71465e+06       10206.3           161   1.71515e+06   

                     8             9   ...            14            15  \
age_group  (27.0, 33.0]  (33.0, 39.0]  ...  (39.0, 45.0]  (45.0, 51.0]   
aggtype            mean         count  ...          mean         count   
Charges         10653.1           151  ...       14083.2           173   

                     16            17            18            19  \
age_group  (45.0, 51.0]  (45.0, 51.0]  (51.0, 57.0]  (51.0, 57.0]   
aggtype             sum          mean         count           sum   
Charges     2.61674e+06       15125.7           163   2.74183e+06   

                     20            21            22            23  
age_group  (51.0, 57.0]  (57.0, 64.0]  (57.0, 64.0]  (57.0, 64.0]  
aggtype            mean         count           sum          mean  
Charges           16821           164   3.24164e+06       19766.1  

[3 rows x 24 columns]

In [6]:
df.T.columns

RangeIndex(start=0, stop=24, step=1)

In [7]:
df.T.index

Index(['age_group', 'aggtype', 'Charges'], dtype='object')

In [8]:
df.values

array([['(17.999, 21.0]', 'count', 194.0],
       ['(17.999, 21.0]', 'sum', 1578891.0817189997],
       ['(17.999, 21.0]', 'mean', 8138.613823293814],
       ['(21.0, 27.0]', 'count', 168.0],
       ['(21.0, 27.0]', 'sum', 1714654.5120400009],
       ['(21.0, 27.0]', 'mean', 10206.276857380955],
       ['(27.0, 33.0]', 'count', 161.0],
       ['(27.0, 33.0]', 'sum', 1715153.6578099998],
       ['(27.0, 33.0]', 'mean', 10653.128309378879],
       ['(33.0, 39.0]', 'count', 151.0],
       ['(33.0, 39.0]', 'sum', 1837265.397780001],
       ['(33.0, 39.0]', 'mean', 12167.320515099344],
       ['(39.0, 45.0]', 'count', 164.0],
       ['(39.0, 45.0]', 'sum', 2309645.98929],
       ['(39.0, 45.0]', 'mean', 14083.207251768292],
       ['(45.0, 51.0]', 'count', 173.0],
       ['(45.0, 51.0]', 'sum', 2616744.3208999992],
       ['(45.0, 51.0]', 'mean', 15125.689716184968],
       ['(51.0, 57.0]', 'count', 163.0],
       ['(51.0, 57.0]', 'sum', 2741825.59526],
       ['(51.0, 57.0]', 'mean', 16821

In [9]:
type(df.values)

numpy.ndarray

In [10]:
nparray = df.values
nparray

array([['(17.999, 21.0]', 'count', 194.0],
       ['(17.999, 21.0]', 'sum', 1578891.0817189997],
       ['(17.999, 21.0]', 'mean', 8138.613823293814],
       ['(21.0, 27.0]', 'count', 168.0],
       ['(21.0, 27.0]', 'sum', 1714654.5120400009],
       ['(21.0, 27.0]', 'mean', 10206.276857380955],
       ['(27.0, 33.0]', 'count', 161.0],
       ['(27.0, 33.0]', 'sum', 1715153.6578099998],
       ['(27.0, 33.0]', 'mean', 10653.128309378879],
       ['(33.0, 39.0]', 'count', 151.0],
       ['(33.0, 39.0]', 'sum', 1837265.397780001],
       ['(33.0, 39.0]', 'mean', 12167.320515099344],
       ['(39.0, 45.0]', 'count', 164.0],
       ['(39.0, 45.0]', 'sum', 2309645.98929],
       ['(39.0, 45.0]', 'mean', 14083.207251768292],
       ['(45.0, 51.0]', 'count', 173.0],
       ['(45.0, 51.0]', 'sum', 2616744.3208999992],
       ['(45.0, 51.0]', 'mean', 15125.689716184968],
       ['(51.0, 57.0]', 'count', 163.0],
       ['(51.0, 57.0]', 'sum', 2741825.59526],
       ['(51.0, 57.0]', 'mean', 16821

In [11]:
nparray.T

array([['(17.999, 21.0]', '(17.999, 21.0]', '(17.999, 21.0]',
        '(21.0, 27.0]', '(21.0, 27.0]', '(21.0, 27.0]', '(27.0, 33.0]',
        '(27.0, 33.0]', '(27.0, 33.0]', '(33.0, 39.0]', '(33.0, 39.0]',
        '(33.0, 39.0]', '(39.0, 45.0]', '(39.0, 45.0]', '(39.0, 45.0]',
        '(45.0, 51.0]', '(45.0, 51.0]', '(45.0, 51.0]', '(51.0, 57.0]',
        '(51.0, 57.0]', '(51.0, 57.0]', '(57.0, 64.0]', '(57.0, 64.0]',
        '(57.0, 64.0]'],
       ['count', 'sum', 'mean', 'count', 'sum', 'mean', 'count', 'sum',
        'mean', 'count', 'sum', 'mean', 'count', 'sum', 'mean', 'count',
        'sum', 'mean', 'count', 'sum', 'mean', 'count', 'sum', 'mean'],
       [194.0, 1578891.0817189997, 8138.613823293814, 168.0,
        1714654.5120400009, 10206.276857380955, 161.0,
        1715153.6578099998, 10653.128309378879, 151.0, 1837265.397780001,
        12167.320515099344, 164.0, 2309645.98929, 14083.207251768292,
        173.0, 2616744.3208999992, 15125.689716184968, 163.0,
        274182

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((2,3),dtype=np.uint32)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint32)

In [27]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [28]:
np.full((5,10),np.NaN)

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

## Numpy NA's vs. Pandas NoneType's

In [31]:
None is np.NaN

False

In [32]:
None == None

True

In [33]:
None == np.NaN

False

In [34]:
np.NaN == np.NaN

False

In [35]:
np.NaN is np.NaN

True

In [36]:
a = np.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [20, 30, 40]])
a.dtype

dtype('float64')

In [37]:
a = np.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], ['20', '30', '40']])
a.dtype

dtype('<U32')

In [38]:
a

array([['1', '2.1', '3'],
       ['4', '5', '6'],
       ['7', '8', '9'],
       ['20', '30', '40']], dtype='<U32')

In [62]:
np.arange(1,10,1/3)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ,
       4.33333333, 4.66666667, 5.        , 5.33333333, 5.66666667,
       6.        , 6.33333333, 6.66666667, 7.        , 7.33333333,
       7.66666667, 8.        , 8.33333333, 8.66666667, 9.        ,
       9.33333333, 9.66666667])

In [63]:
np.arange(1,10,1/3).shape

(27,)

In [66]:
ar3by9 = np.arange(1,10,1/3).reshape(3,9)
ar3by9

array([[1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
        2.66666667, 3.        , 3.33333333, 3.66666667],
       [4.        , 4.33333333, 4.66666667, 5.        , 5.33333333,
        5.66666667, 6.        , 6.33333333, 6.66666667],
       [7.        , 7.33333333, 7.66666667, 8.        , 8.33333333,
        8.66666667, 9.        , 9.33333333, 9.66666667]])

In [67]:
ar3by9.shape

(3, 9)

In [69]:
ar3by9.reshape(9,3)

array([[1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667],
       [3.        , 3.33333333, 3.66666667],
       [4.        , 4.33333333, 4.66666667],
       [5.        , 5.33333333, 5.66666667],
       [6.        , 6.33333333, 6.66666667],
       [7.        , 7.33333333, 7.66666667],
       [8.        , 8.33333333, 8.66666667],
       [9.        , 9.33333333, 9.66666667]])

In [70]:
ar3by9.reshape(9,3).shape

(9, 3)

In [79]:
np.linspace(1.0, 2.0, 9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [80]:
np.linspace(1.0, 2.0, 9).shape

(9,)

In [81]:
np.arange(1,9,1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.linspace(1.0, 10.0, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [83]:
np.linspace(1.0, 10.0, 9).reshape((3,3))

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [86]:
a  = np.array( [[5, 10, 15], [2, 4, 6], [3, 6, 9, ],])
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [88]:
b = np.array( [
[10, 85, 92], [77, 16, 14], [19, 52, 23],
] )
b

array([[10, 85, 92],
       [77, 16, 14],
       [19, 52, 23]])

In [89]:
b.shape

(3, 3)

In [94]:
b + 1000

array([[1010, 1085, 1092],
       [1077, 1016, 1014],
       [1019, 1052, 1023]])

In [97]:
a + b

array([[ 15,  95, 107],
       [ 79,  20,  20],
       [ 22,  58,  32]])

In [104]:
a.sum()

60

In [105]:
b.sum()

388

In [107]:
np.sum(b)

388

In [108]:
sum(b)

array([106, 153, 129])

In [116]:
b.T

array([[10, 77, 19],
       [85, 16, 52],
       [92, 14, 23]])

In [115]:
b.transpose()

array([[10, 77, 19],
       [85, 16, 52],
       [92, 14, 23]])

In [117]:
b.ravel()

array([10, 85, 92, 77, 16, 14, 19, 52, 23])

In [118]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

Indexing

In [123]:
a[0,1]

10

Slicing

In [127]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [126]:
a[0:2,1:]

array([[10, 15],
       [ 4,  6]])

In [130]:
c = a.ravel()
c

array([ 5, 10, 15,  2,  4,  6,  3,  6,  9])

In [132]:
c.shape

(9,)

In [134]:
boolean_mask = [True,True,True,False,False,False,False,False,False]
c[boolean_mask]

array([ 5, 10, 15])

In [135]:
c > 5

array([False,  True,  True, False, False,  True, False,  True,  True])

In [136]:
c[c > 5]

array([10, 15,  6,  6,  9])

In [137]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [143]:
a[[True,True,False]]

array([[ 5, 10, 15],
       [ 2,  4,  6]])

In [149]:
a.sum()

60

In [147]:
df.count()

age_group    24
aggtype      24
Charges      24
dtype: int64

In [154]:
for row in a:
    print(row.mean()>5)

True
False
True


In [156]:
a[[row.mean()>5 for row in a]]

array([[ 5, 10, 15],
       [ 3,  6,  9]])

Matrix Operations

In [159]:
m1 = np.array( [[2, 4, 6],
[10, 20, 30]] )
m2 = np.array([[1, 15], [3, 25],
[5, 35]]) 

In [164]:
m1.shape

(2, 3)

In [165]:
m2.shape

(3, 2)

In [166]:
m2 + 5

array([[ 6, 20],
       [ 8, 30],
       [10, 40]])

In [163]:
m1 * 10

array([[ 20,  40,  60],
       [100, 200, 300]])

In [167]:
m1 @ m2

array([[  44,  340],
       [ 220, 1700]])

In [168]:
m2 @ m1

array([[ 152,  304,  456],
       [ 256,  512,  768],
       [ 360,  720, 1080]])

In [170]:
np.savetxt("m2_numpy_array.txt", m2, delimiter=",", fmt="%d")
print("done")

done


In [174]:
m3 = np.loadtxt("m2_numpy_array.txt", delimiter=",")
m3

array([[ 1., 15.],
       [ 3., 25.],
       [ 5., 35.]])